adminUser:
  password: vault:thumbcute/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:thumbcute/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:thumbcute/prow:hmacToken
